//! Functions and structs to handle fonts in PDFs.

use std::collections::HashMap;
use std::sync::LazyLock;

use lopdf::{Document, Object};
use ordered_float::OrderedFloat;

use crate::{
    math::{from_cmex, from_cmmi, from_cmsy, from_msbm},
    parse::{PageID, PdfError},
};

/// A struct to keep track of font size changes. This includes all the metadata you might need
/// about font changes. The primary purpose of this is to track sections, subsections, etc., but
/// the additional metadata here can also be used to chunk text by section.
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub(crate) struct FontSizeMarker {
    /// 0-indexed page number. Initialized after the full PDF is parsed.
    pub page_number: usize,
    /// Byte index into the extracted text
    pub byte_index: usize,
    /// The font size in points
    pub font_size: OrderedFloat<f32>,
    /// Font name (e.g., "CMR10", "CMBX12")
    pub font_name: String,
}

/// A type to convert from bytes in math fonts to LaTeX code
type ByteTransformFn = fn(u8) -> std::borrow::Cow<'static, str>;

/// A zero-allocation iterator for octal escape sequences and raw bytes. This is useful for parsing
/// octal escape codes that are used in math fonts when non-printable characters are used to
/// represent symbols.
pub(crate) struct IterCodepoints<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl Iterator for IterCodepoints<'_> {
    type Item = u8;

    fn next(&mut self) -> Option<u8> {
        if self.pos >= self.bytes.len() {
            return None;
        }
        let b = self.bytes[self.pos];
        if b == b'\\' {
            // Possible octal escape
            let rem = self.bytes.len() - self.pos;
            if rem >= 4  // Length of octal escape sequence
                && self.bytes[self.pos + 1] == b'0'
                && self.bytes[self.pos + 2].is_ascii_digit()
                && self.bytes[self.pos + 2] < b'8'
                && self.bytes[self.pos + 3].is_ascii_digit()
                && self.bytes[self.pos + 3] < b'8'
            {
                let oct = &self.bytes[self.pos + 1..=self.pos + 3];
                let code = (oct[1] - b'0') * 8 + (oct[2] - b'0');
                self.pos += 4;
                Some(code)
            } else {
                // Just a backslash or malformed escape
                self.pos += 1;
                Some(b'\\')
            }
        } else {
            self.pos += 1;
            Some(b)
        }
    }
}

pub(crate) fn font_transform(input: &str, transform: ByteTransformFn) -> String {
    IterCodepoints {
        bytes: input.as_bytes(),
        pos: 0,
    }
    .map(transform)
    .collect::<String>()
}

/// A lazy-loaded hashmap storing conversions from math fonts to LaTeX code
/// Handles most common math fonts, but does not yet support specialized math fonts.
pub(crate) static FONT_TRANSFORMS: LazyLock<HashMap<&'static str, ByteTransformFn>> =
    LazyLock::new(|| {
        let mut m: HashMap<&'static str, ByteTransformFn> = HashMap::new();

        m.insert("CMMI5", from_cmmi);
        m.insert("CMMI6", from_cmmi);
        m.insert("CMMI7", from_cmmi);
        m.insert("CMMI8", from_cmmi);
        m.insert("CMMI9", from_cmmi);
        m.insert("CMMI10", from_cmmi);
        m.insert("CMMI12", from_cmmi);

        m.insert("CMSY5", from_cmsy);
        m.insert("CMSY6", from_cmsy);
        m.insert("CMSY7", from_cmsy);
        m.insert("CMSY8", from_cmsy);
        m.insert("CMSY9", from_cmsy);
        m.insert("CMSY10", from_cmsy);

        m.insert("CMEX10", from_cmex);

        m.insert("MSBM5", from_msbm);
        m.insert("MSBM6", from_msbm);
        m.insert("MSBM7", from_msbm);
        m.insert("MSBM8", from_msbm);
        m.insert("MSBM9", from_msbm);
        m.insert("MSBM10", from_msbm);

        m
    });

/// The mappings of a ToUnicode CMap. For now, we do not support other kinds of CMaps.
pub(crate) type CMap = HashMap<String, String>;

/// The type of encoding used by a font. Either `SIMPLE` (human-readable) or `CID_KEYED`
/// (Unicode/glyph ID-encoded)
#[derive(Debug)]
pub(crate) enum FontEncoding {
    /// Human-readable, "simple" encoding. Under this encoding, each TJ block has contents that can
    /// be parsed as plain text.
    Simple,
    /// CID-keyed, or glyph ID-encoded font. For this encoding, the font usually is a subsetted
    /// embedded font (i.e., a CID-keyed subset of a font that's embedded), and we need to check
    /// the `ToUnicode` CMap for that font. It is possible to also use non-ToUnicode CMaps; we do
    /// not yet handle this case.
    ///
    /// Modern PDFs, such as those generated by `pdflatex`, use CID-keyed font subsets, with
    /// two-byte (or multi-byte, but we don't yet handle this) CIDs, custom glyph ID maps, and
    /// `ToUnicode` CMaps for real text extraction.
    CIDKeyed(CMap),
}

/// CMaps can take two main forms: individual, where `beginbfchar` and `endbfchar` wrap a set of
/// lines, each with two tokens; and ranged, where `beginbfrange` and `endbfrange` wrap a set of
/// triples. The first two tokens in the triples mark begin and end of a range, and the third token
/// can be in hex form or an array (currently, not yet supported).
#[derive(Debug, PartialEq)]
enum CMapKind {
    Individual,
    Ranged,
    Unknown,
}

/// Given a PDF `Document` reference, a page ID, and a font key (e.g., "F19"), return the font
/// object.
///
/// # Arguments
///
/// * `doc` - The `lopdf::Document` object.
/// * `page_id` - The `lopdf` page ID. Different pages can have different font dictionaries,
///   otherwise operations such as joining PDFs would be more complicated than they already are.
/// * `font_key` - The font key as used in the PDF content stream.
///
/// # Returns
///
/// A `HashMap` with string keys mapping to `lopdf::Object` references.
///
/// # Errors
///
/// * `PdfError::PageFontError` if getting page fonts failed.
/// * `PdfError::FontNotFound` if the font key does not exist.
///
/// # Panics
///
/// * If any of the keys in the font dictionary are not valid UTF-8.
pub(crate) fn get_font<'a>(
    doc: &'a Document,
    page_id: PageID,
    font_key: &str,
) -> Result<HashMap<&'a str, &'a Object>, PdfError> {
    // Get the font dictionary for the page
    let fonts = doc
        .get_page_fonts(page_id)
        .map_err(|_| PdfError::PageFontError)?;

    let font_obj = fonts
        .get(font_key.as_bytes())
        .ok_or(PdfError::FontNotFound(font_key.into()))?;
    let font_hash = font_obj.as_hashmap();

    font_hash
        .iter()
        .map(|(k, v)| {
            let key_str = std::str::from_utf8(k)?;
            Ok((key_str, v))
        })
        .collect::<Result<_, _>>()
}

/// Parse a CMap string. A font key is taken as reference to provide more context in errors.
///
/// Currently, this CMap parser supports scenarios with one block of mappings per font, and only
/// supports `beginbfchar`..`endbfchar` and `beginbfrange`..`endbfrange`s, i.e., it does not support
/// more complex use cases such as those involving `begincidrange`..`endcidrange`. Note that per
/// ISO 32000-1:2008, §9.7.5.4(e), `beginrearrangedfont`..`endrearrangedfont` should not be used in
/// embedded CMaps; moreover, `usefont`s should only specify a font number of 0.
#[allow(clippy::too_many_lines)]
pub(crate) fn parse_cmap(cmap: &str, font_key: &str) -> Result<HashMap<String, String>, PdfError> {
    // TODO: (ZOT-202) Technically, the number of entries in each block is limited to 100,
    // so a CID mapping can have multiple blocks. We should parse all such blocks, not just
    // the first.

    let cmap_kind = if cmap.contains("beginbfchar") {
        CMapKind::Individual
    } else if cmap.contains("beginbfrange") {
        CMapKind::Ranged
    } else {
        CMapKind::Unknown
    };

    match cmap_kind {
        CMapKind::Unknown => Err(PdfError::EncodingError(format!(
            "CMap type for {font_key} could not be determined."
        ))),
        CMapKind::Individual => {
            let csrange_begin = cmap.find("beginbfchar").unwrap() + "beginbfchar".len();
            let csrange_end = cmap
                .find("endbfchar")
                .ok_or(PdfError::EncodingError(format!(
                    "Deflated ToUnicode CMap for font {font_key} has no `endbfchar`."
                )))?;

            let csrange = cmap[csrange_begin..csrange_end].trim();
            let lines = csrange.split('\n');

            let mut mappings = HashMap::new();

            // Within the CMap, each line has the following form:
            //   <001B> <0041>
            // In this case, the 2-byte CID 001B maps to U+0041.
            for line in lines {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() != 2 {
                    log::warn!(
                        "In CMap for {font_key}, unexpected line with {} tokens.",
                        parts.len()
                    );
                    continue;
                }

                let cid = parts[0].trim_matches(|c| c == '<' || c == '>');

                // In some cases, `parts[1]` can have multiple Unicode code points. This is
                // sometimes done to handle ligatures, among others. For example, the ligature
                // `ff` is represented as two U+066 code points.
                let code_units: Vec<u16> = parts[1]
                    .trim_matches(|c| c == '<' || c == '>')
                    .as_bytes()
                    .chunks_exact(4)
                    .map(|chunk| u16::from_str_radix(std::str::from_utf8(chunk).unwrap(), 16))
                    .collect::<Result<_, _>>()
                    .map_err(|_| PdfError::InvalidUtf8)?;

                let unicode: String = std::char::decode_utf16(code_units)
                    .map(|r| r.map_err(|e| PdfError::EncodingError(format!("Invalid UTF-16: {e}"))))
                    .collect::<Result<_, _>>()?;

                mappings.insert(cid.to_string().to_lowercase(), unicode);
            }

            Ok(mappings)
        }
        CMapKind::Ranged => {
            let csrange_begin = cmap.find("beginbfrange").unwrap() + "beginbfrange".len();
            let csrange_end = cmap
                .find("endbfrange")
                .ok_or(PdfError::EncodingError(format!(
                    "Deflated ToUnicode CMap for font {font_key} has no `endbfrange`."
                )))?;

            let csrange = cmap[csrange_begin..csrange_end].trim();
            let lines = csrange.split('\n');

            let mut mappings = HashMap::new();

            // Within the CMap, each line has the following form:
            //   <000B> <000C> <0028>
            // In this case, we have:
            //   * CID 000B -> U+0028
            //   * CID 000C -> U+0029
            for line in lines {
                if line.contains('[') {
                    log::error!("CMaps with `bfrange`s that contain arrays are not yet supported.");
                    return Err(PdfError::EncodingError(
                        "Unsupported CID map with arrays in range.".into(),
                    ));
                }

                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() != 3 {
                    log::warn!(
                        "In CMap for {font_key}, unexpected line with {} tokens.",
                        parts.len()
                    );
                    continue;
                }

                let start_cid = parts[0].trim_matches(|c| c == '<' || c == '>');
                let end_cid = parts[1].trim_matches(|c| c == '<' || c == '>');

                let start_cid_u16 = u16::from_str_radix(start_cid, 16).map_err(|_| {
                    PdfError::EncodingError(format!(
                        "In CMap for {font_key}, CID {start_cid} was not valid UTF-16"
                    ))
                })?;
                let end_cid_u16 = u16::from_str_radix(end_cid, 16).map_err(|_| {
                    PdfError::EncodingError(format!(
                        "In CMap for {font_key}, CID {end_cid} was not valid UTF-16"
                    ))
                })?;

                // Again, parts[2] can have multiple UTF-16BE code units. In this case, for each
                // consecutive code in the source code range, we increment the last byte of the
                // string, see the PDF standard, ISO 32000-1:2008, §9.10.3 ("ToUnicode CMaps").
                // This means that we don't treat the hex string as one Big Endian integer, and only
                // look at the last byte for the purposes of the range.
                let mut code_units: Vec<u16> = parts[2]
                    .trim_matches(|c| c == '<' || c == '>')
                    .as_bytes()
                    .chunks_exact(4)
                    .map(|chunk| u16::from_str_radix(std::str::from_utf8(chunk).unwrap(), 16))
                    .collect::<Result<_, _>>()
                    .map_err(|_| PdfError::InvalidUtf8)?;

                let original_last = code_units.last().copied();
                for i in start_cid_u16..=end_cid_u16 {
                    if let (Some(c), Some(orig)) = (code_units.last_mut(), original_last) {
                        // Technically, this is supposed to be *byte* addition, so it's not
                        // to-spec, but this is good enough.
                        *c = orig.checked_add(i - start_cid_u16).ok_or_else(|| {
                            PdfError::EncodingError(format!(
                                "In CMap for {font_key}, ranged destination overflowed u16"
                            ))
                        })?;
                    }
                    let unicode: String = std::char::decode_utf16(code_units.iter().copied())
                        .map(|r| {
                            r.map_err(|e| PdfError::EncodingError(format!("Invalid UTF-16: {e}")))
                        })
                        .collect::<Result<_, _>>()?;
                    mappings.insert(format!("{i:04x}"), unicode);
                }
            }

            Ok(mappings)
        }
    }
}

/// Attempt to get the font encoding for a font key on a specific page.
///
/// This function uses heuristics to determine whether a font is likely to be "simple" (i.e.,
/// can be parsed as plain-text), or needs to be translated via a corresponding CMap.
///
/// # Returns
///
/// If the specified font is a CID-keyed font, returns `FontEncoding::CIDKeyed` with a
/// reference to the `ToUnicode` CMap. Otherwise, returns `FontEncoding::Simple`.
///
/// # Errors
///
/// * `PdfError::PageFontError` if getting page fonts failed.
/// * `PdfError::FontNotFound` if the font key does not exist.
/// * `PdfError::EncodingError` if the font dictionary:
///      * Has an /Encoding that could not be read
///      * Indicates a CID-keyed font but does not have a ToUnicode CMap.
///      * Has a ToUnicode CMap that could not be read or deflated.
///      * Has a ToUnicode CMap without a `beginbfchar`, `endbfchar`, `beginbfrange`, or
///        `endbfrange` marker.
/// * `PdfError::InternalError` if the font dictionary:
///      * Does not have a /Subtype that could be read.
///      * Has a /ToUnicode reference that is invalid.
/// * `PdfError::InvalidUtf8` if the deflated ToUnicode CMap is not valid UTF-8.
///
/// # Panics
///
/// * If any of the keys in the font dictionary are not valid UTF-8.
pub(crate) fn compute_font_encoding(
    doc: &Document,
    page_id: PageID,
    font_key: &str,
) -> Result<FontEncoding, PdfError> {
    let font_obj = get_font(doc, page_id, font_key)?;

    // Test 1: if the font has:
    //   /Subtype /Type1
    //   /Subtype /TrueType
    // then it is likely a "simple" font.
    let font_subtype = str::from_utf8(
        font_obj
            .get("Subtype")
            .ok_or(PdfError::MissingSubtype)?
            .as_name()
            .map_err(|_| {
                PdfError::InternalError(format!(
                    "Expected font {font_key}'s Subtype key to be a `name`"
                ))
            })?,
    )
    .map_err(|e| {
        PdfError::InternalError(format!(
            "Font {font_key}'s Subtype value is not valid UTF-8: {e}"
        ))
    })?;

    if ["Type1", "TrueType"].contains(&font_subtype) {
        return Ok(FontEncoding::Simple);
    }

    // Test 2: if the font has:
    //   /Encoding /Identity-H
    //   /Encoding /Identity-V
    // then it is likely a CID-keyed font. However, if it has:
    //   /Encoding /WinAnsiEncoding
    //   /Encoding /MacRomanEncoding
    // it is likely a "simple" font.
    let Some(font_encoding) = font_obj.get("Encoding") else {
        log::warn!(
            "Could not determine font type for {font_key}, assuming simple. This may be wrong."
        );
        return Ok(FontEncoding::Simple);
    };
    let font_encoding = str::from_utf8(font_encoding.as_name().map_err(|_| {
        PdfError::EncodingError(format!(
            "Expected font {font_key}'s Encoding key to be a `name`"
        ))
    })?)
    .map_err(|e| {
        PdfError::EncodingError(format!(
            "Font {font_key}'s Encoding name is not valid UTF-8: {e}"
        ))
    })?;

    if ["WinAnsiEncoding", "MacRomanEncoding"].contains(&font_encoding) {
        Ok(FontEncoding::Simple)
    } else if ["Identity-H", "Identity-V"].contains(&font_encoding) || font_encoding == "Type0" {
        // Test 3: if the font has:
        //   /Subtype /Type0
        // then it is likely a CID-keyed font.
        let cmap_ref = font_obj
            .get("ToUnicode")
            .ok_or(PdfError::EncodingError(format!(
                "CID-keyed font {font_key} does not have a ToUnicode CMap.",
            )))?
            .as_reference()
            .map_err(|_| {
                PdfError::EncodingError(format!(
                    "CID-keyed font {font_key}'s ToUnicode CMap could not be read."
                ))
            })?;

        let decompressed = doc
            .get_object(cmap_ref)
            .map_err(|_| {
                PdfError::InternalError(format!(
                    "Font {font_key}'s ToUnicode CMap points to invalid reference.",
                ))
            })?
            .as_stream()
            .map_err(|_| {
                PdfError::EncodingError(format!(
                    "CID-keyed font {font_key}'s ToUnicode CMap could not be read."
                ))
            })?
            .decompressed_content()
            .map_err(|_| {
                PdfError::EncodingError(format!(
                    "CID-keyed font {font_key}'s ToUnicode CMap could not be deflated."
                ))
            })?;

        let cmap = String::from_utf8(decompressed).map_err(|_| PdfError::InvalidUtf8)?;
        let mappings = parse_cmap(&cmap, font_key)?;

        Ok(FontEncoding::CIDKeyed(mappings))
    } else {
        // If we got here, then we don't have a good idea; emit a warning and assume Simple.
        log::warn!(
            "No heuristic matched for font {font_key}; assuming simple. This is likely wrong."
        );
        Ok(FontEncoding::Simple)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_cmap_ranged() {
        // A range that walks from CID 000B to 000C, mapping the last code unit upward from
        // U+0028 ('('). So 000B -> '(' and 000C -> ')'.
        let cmap = "\
1 beginbfrange
<000b> <000c> <0028>
endbfrange";

        let mappings = parse_cmap(cmap, "F1").expect("ranged CMap should parse");

        assert_eq!(mappings.len(), 2);
        assert_eq!(mappings.get("000b"), Some(&"(".to_string()));
        assert_eq!(mappings.get("000c"), Some(&")".to_string()));
    }

    #[test]
    fn test_parse_cmap_ranged_multi_entry() {
        // Two ranges in a single block, with the start CID and Unicode code points not aligned.
        // The first range maps 0041..=0043 onto 'a'..='c'; the second maps a single CID 0050 to 'Z'.
        let cmap = "\
2 beginbfrange
<0041> <0043> <0061>
<0050> <0050> <005a>
endbfrange";

        let mappings = parse_cmap(cmap, "F2").expect("ranged CMap should parse");

        assert_eq!(mappings.len(), 4);
        assert_eq!(mappings.get("0041"), Some(&"a".to_string()));
        assert_eq!(mappings.get("0042"), Some(&"b".to_string()));
        assert_eq!(mappings.get("0043"), Some(&"c".to_string()));
        assert_eq!(mappings.get("0050"), Some(&"Z".to_string()));
    }

    #[test]
    fn test_parse_cmap_ranged_rejects_arrays() {
        // Array destinations in a `bfrange` are not yet supported and must surface an error
        // rather than silently dropping the line.
        let cmap = "\
1 beginbfrange
<0001> <0003> [<0041> <0042> <0043>]
endbfrange";

        let err = parse_cmap(cmap, "F3").expect_err("array ranges are unsupported");
        assert!(matches!(err, PdfError::EncodingError(_)));
    }

    #[test]
    fn test_parse_cmap_ranged_missing_end_marker() {
        // A `beginbfrange` without its matching `endbfrange` is an error.
        let cmap = "\
1 beginbfrange
<000b> <000c> <0028>";

        let err = parse_cmap(cmap, "F4").expect_err("missing endbfrange should error");
        assert!(matches!(err, PdfError::EncodingError(_)));
    }
}
