name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on:
      group: all-repos

    steps:
    - name: Dependencies
      run: sudo apt install protobuf-compiler
    - uses: rui314/setup-mold@v1
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
      env:
        ANTHROPIC_KEY: ${{ secrets.ANTHROPIC_KEY }}
        VOYAGE_AI_API_KEY: ${{ secrets.VOYAGE_AI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_MODEL: claude-3-haiku-20240307
        OPENAI_EMBEDDING_MODEL: text-embedding-3-small
        MAX_CONCURRENT_REQUESTS: 5
